/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ekatas_soundtest_MainActivity */

#ifndef _Included_com_ekatas_soundtest_MainActivity
#define _Included_com_ekatas_soundtest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ekatas_soundtest_MainActivity
 * Method:    outputSound
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_com_ekatas_soundtest_MainActivity_outputSound
  (JNIEnv *env, jobject thiz);

/*
 * Class:     com_ekatas_soundtest_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ekatas_soundtest_MainActivity_stringFromJNI
  (JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
